import getBestTimeSurfBeach from "../data_manipulation/getBestTimeSurfBeach";
const generateBeachReport = require("./specificBeachScrap");

const mockData = [
  {
    name: "Chapa",
    data: {
      today: [
        {
          id: "dawn",
          status: "success",
          meters: "0.4-0.6m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "ESE - 102°",
          wind: {
            direction: "Moderate, Offshore NNW - 341°",
            min: " 17 ",
            max: "    24  kph ",
          },
        },
        {
          id: "midMorning",
          status: "success",
          meters: "0.4-0.6m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "E - 100°",
          wind: {
            direction: "Gentle, Offshore N - 8°",
            min: " 11 ",
            max: "    15  kph ",
          },
        },
        {
          id: "noon",
          status: "success",
          meters: "0.4-0.7m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.5m  ",
          period: "  8s  ",
          swellDirection: "S - 182°",
          wind: {
            direction: "Gentle, Cross/Offshore NE - 47°",
            min: " 15 ",
            max: "    18  kph ",
          },
        },
        {
          id: "afternoon",
          status: "warning",
          meters: "0.4-0.7m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.6m  ",
          period: "  8s  ",
          swellDirection: "S - 189°",
          wind: {
            direction: "Fresh, Cross/Onshore ENE - 61°",
            min: " 28 ",
            max: "    28  kph ",
          },
        },
        {
          id: "sunset",
          status: "warning",
          meters: "0.4-0.6m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.5m  ",
          period: "  8s  ",
          swellDirection: "S - 190°",
          wind: {
            direction: "Fresh, Cross/Offshore NE - 47°",
            min: " 28 ",
            max: "    40  kph ",
          },
        },
      ],
      tomorrow: [
        {
          id: "dawn",
          status: "success",
          meters: "0.3-0.5m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.4m  ",
          period: "  9s  ",
          swellDirection: "S - 190°",
          wind: {
            direction: "Moderate, Offshore N - 7°",
            min: " 17 ",
            max: "    26  kph ",
          },
        },
        {
          id: "midMorning",
          status: "success",
          meters: "0.3-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.3m  ",
          period: "  9s  ",
          swellDirection: "ESE - 105°",
          wind: {
            direction: "Moderate, Offshore NNE - 15°",
            min: " 17 ",
            max: "    23  kph ",
          },
        },
        {
          id: "noon",
          status: "success",
          meters: "0.3-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.3m  ",
          period: "  9s  ",
          swellDirection: "ESE - 107°",
          wind: {
            direction: "Moderate, Cross/Offshore NE - 48°",
            min: " 18 ",
            max: "    21  kph ",
          },
        },
        {
          id: "afternoon",
          status: "warning",
          meters: "0.3-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.2m  ",
          period: "  13s  ",
          swellDirection: "SSE - 164°",
          wind: {
            direction: "Moderate, Cross/Onshore ENE - 63°",
            min: " 27 ",
            max: "    27  kph ",
          },
        },
        {
          id: "sunset",
          status: "warning",
          meters: "0.3-0.5m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.3m  ",
          period: "  12s  ",
          swellDirection: "SSE - 164°",
          wind: {
            direction: "Fresh, Cross/Offshore NE - 49°",
            min: " 28 ",
            max: "    40  kph ",
          },
        },
      ],
    },
  },
  {
    name: "Serena",
    data: {
      today: [
        {
          id: "dawn",
          status: "success",
          meters: "0.4-0.6m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.6m  ",
          period: "  7s  ",
          swellDirection: "S - 185°",
          wind: {
            direction: "Moderate, Offshore NW - 326°",
            min: " 17 ",
            max: "    24  kph ",
          },
        },
        {
          id: "midMorning",
          status: "success",
          meters: "0.4-0.6m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "E - 100°",
          wind: {
            direction: "Gentle, Offshore N - 353°",
            min: " 13 ",
            max: "    16  kph ",
          },
        },
        {
          id: "noon",
          status: "success",
          meters: "0.4-0.7m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.5m  ",
          period: "  8s  ",
          swellDirection: "S - 182°",
          wind: {
            direction: "Gentle, Cross/Offshore NE - 43°",
            min: " 17 ",
            max: "    19  kph ",
          },
        },
        {
          id: "afternoon",
          status: "warning",
          meters: "0.4-0.7m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.6m  ",
          period: "  8s  ",
          swellDirection: "S - 189°",
          wind: {
            direction: "Moderate, Cross/Onshore ENE - 67°",
            min: " 24 ",
            max: "    26  kph ",
          },
        },
        {
          id: "sunset",
          status: "warning",
          meters: "0.4-0.6m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.5m  ",
          period: "  8s  ",
          swellDirection: "S - 190°",
          wind: {
            direction: "Fresh, Cross/Offshore NE - 48°",
            min: " 26 ",
            max: "    36  kph ",
          },
        },
      ],
      tomorrow: [
        {
          id: "dawn",
          status: "success",
          meters: "0.4-0.6m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.4m  ",
          period: "  9s  ",
          swellDirection: "S - 190°",
          wind: {
            direction: "Gentle, Offshore N - 349°",
            min: " 12 ",
            max: "    18  kph ",
          },
        },
        {
          id: "midMorning",
          status: "success",
          meters: "0.3-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.4m  ",
          period: "  8s  ",
          swellDirection: "SSW - 195°",
          wind: {
            direction: "Gentle, Offshore N - 11°",
            min: " 14 ",
            max: "    21  kph ",
          },
        },
        {
          id: "noon",
          status: "success",
          meters: "0.3-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.3m  ",
          period: "  8s  ",
          swellDirection: "SSW - 194°",
          wind: {
            direction: "Moderate, Cross/Offshore NE - 53°",
            min: " 19 ",
            max: "    21  kph ",
          },
        },
        {
          id: "afternoon",
          status: "warning",
          meters: "0.3-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.2m  ",
          period: "  13s  ",
          swellDirection: "SSE - 164°",
          wind: {
            direction: "Moderate, Cross-shore ENE - 63°",
            min: " 26 ",
            max: "    27  kph ",
          },
        },
        {
          id: "sunset",
          status: "warning",
          meters: "0.3-0.5m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.3m  ",
          period: "  12s  ",
          swellDirection: "SSE - 164°",
          wind: {
            direction: "Fresh, Cross/Offshore NE - 52°",
            min: " 26 ",
            max: "    40  kph ",
          },
        },
      ],
    },
  },
  {
    name: "Cardiel",
    data: {
      today: [
        {
          id: "dawn",
          status: "success",
          meters: "0.5-0.7m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "ESE - 101°",
          wind: {
            direction: "Moderate, Offshore NW - 326°",
            min: " 17 ",
            max: "    24  kph ",
          },
        },
        {
          id: "midMorning",
          status: "success",
          meters: "0.5-0.8m",
          activeStars: 1,
          inactiveStars: 0,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "E - 94°",
          wind: {
            direction: "Gentle, Cross/Offshore N - 353°",
            min: " 13 ",
            max: "    16  kph ",
          },
        },
        {
          id: "noon",
          status: "warning",
          meters: "0.5-0.8m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "E - 93°",
          wind: {
            direction: "Gentle, Onshore NE - 43°",
            min: " 17 ",
            max: "    19  kph ",
          },
        },
        {
          id: "afternoon",
          status: "danger",
          meters: "0.5-0.7m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "E - 95°",
          wind: {
            direction: "Moderate, Onshore ENE - 67°",
            min: " 24 ",
            max: "    26  kph ",
          },
        },
        {
          id: "sunset",
          status: "danger",
          meters: "0.4-0.7m",
          activeStars: 0,
          inactiveStars: 1,
          averageMeters: "  0.5m  ",
          period: "  10s  ",
          swellDirection: "E - 95°",
          wind: {
            direction: "Fresh, Onshore NE - 48°",
            min: " 26 ",
            max: "    36  kph ",
          },
        },
      ],
      tomorrow: [
        {
          id: "dawn",
          status: "success",
          meters: "0.3-0.5m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.3m  ",
          period: "  9s  ",
          swellDirection: "ESE - 106°",
          wind: {
            direction: "Gentle, Cross/Offshore N - 349°",
            min: " 12 ",
            max: "    18  kph ",
          },
        },
        {
          id: "midMorning",
          status: "warning",
          meters: "0.3-0.5m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.3m  ",
          period: "  9s  ",
          swellDirection: "ESE - 107°",
          wind: {
            direction: "Gentle, Cross/Onshore N - 11°",
            min: " 14 ",
            max: "    21  kph ",
          },
        },
        {
          id: "noon",
          status: "warning",
          meters: "0.3-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.3m  ",
          period: "  9s  ",
          swellDirection: "ESE - 108°",
          wind: {
            direction: "Moderate, Onshore NE - 53°",
            min: " 19 ",
            max: "    21  kph ",
          },
        },
        {
          id: "afternoon",
          status: "danger",
          meters: "0.2-0.4m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.2m  ",
          period: "  9s  ",
          swellDirection: "ESE - 109°",
          wind: {
            direction: "Moderate, Onshore ENE - 63°",
            min: " 26 ",
            max: "    27  kph ",
          },
        },
        {
          id: "sunset",
          status: "danger",
          meters: "0.3-0.5m",
          activeStars: 0,
          inactiveStars: 0,
          averageMeters: "  0.7m  ",
          period: "  4s  ",
          swellDirection: "NE - 50°",
          wind: {
            direction: "Fresh, Onshore NE - 52°",
            min: " 26 ",
            max: "    40  kph ",
          },
        },
      ],
    },
  },
];

const beachs = [
  {
    name: "Chapa",
    url: "https://magicseaweed.com/Las-Cuevas-La-Popular-Surf-Report/1159/",
  },
  { name: "Serena", url: "https://magicseaweed.com/Serena-Surf-Report/1287/" },
  {
    name: "Cardiel",
    url: "https://magicseaweed.com/La-Pepita-Surf-Report/2707/",
  },
];
const main = () => {
  return getBestTimeSurfBeach(mockData);
  return Promise.all(
    beachs.map(async (beach) => {
      const data = await generateBeachReport(beach);
      //TODO: check the name of the beach if this doesnt work
      return data;
    })
  ).then((beachsResponse) => {
    const response = getBestTimeSurfBeach(beachsResponse);
    console.log(JSON.stringify(response));
    return response;
  });
};

module.exports = main;
