import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import BeachItem from "../components/BeachItem";
import { beachs } from "../server_src/domain/Beach";
import styles from "../styles/Home.module.css";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

const Home: NextPage = () => {
  const { data, error } = useSWR("/api/forecast", fetcher);

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;

  const { today, tomorrow } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Surf spots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Surf spots</h1>

        <p className={styles.description}>Hoy</p>
        <div style={{ width: "100%", textAlign: "start" }}>
          <hr />
          <div>
            {" "}
            <div> 6 am </div> <BeachItem data={today.dawn} />
          </div>
          <hr />
          <div>
            <div>9 am </div> <BeachItem data={today.midMorning} />
          </div>
          <hr />
          <div>
            <div>12 pm </div> <BeachItem data={today.noon} />
          </div>
          <hr />
          <div>
            <div> 3 pm </div> <BeachItem data={today.afternoon} />
          </div>
          <hr />
          <div>
            <div>6 pm </div> <BeachItem data={today.sunset} />
          </div>
          <hr />
        </div>

        <p className={styles.description}>Mañana</p>
        <div style={{ width: "100%", textAlign: "start" }}>
          <hr />
          <div>
            {" "}
            <div> 6 am </div> <BeachItem data={tomorrow.dawn} />
          </div>
          <hr />
          <div>
            <div>9 am </div> <BeachItem data={tomorrow.midMorning} />
          </div>
          <hr />
          <div>
            <div>12 pm </div> <BeachItem data={tomorrow.noon} />
          </div>
          <hr />
          <div>
            <div> 3 pm </div> <BeachItem data={tomorrow.afternoon} />
          </div>
          <hr />
          <div>
            <div>6 pm </div> <BeachItem data={tomorrow.sunset} />
          </div>
          <hr />
        </div>

        <h2> Playas</h2>
        {beachs.map((beach) => (
          <a href={beach.url} style={{ width: "100%" }}>
            <h2>{beach.name} &rarr;</h2>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Gonzalo Gras Cantou
        </a>
      </footer>
    </div>
  );
};

export default Home;
