import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import BeachItem from "../components/BeachItem";
import Loader from "../components/Loader";
import { beachs } from "../server_src/domain/Beach";
import styles from "../styles/Home.module.css";

const dayHours = [
  {
    label: "6 AM",
    id: "dawn",
  },
  {
    label: "9 AM",
    id: "midMorning",
  },
  {
    label: "12 PM",
    id: "noon",
  },
  {
    label: "3 PM",
    id: "afternoon",
  },
  {
    label: "6 PM",
    id: "sunset",
  },
];
const fetcher = (...args) => fetch(...args).then((res) => res.json());

const Home: NextPage = () => {
  const { data, error } = useSWR("/api/forecast", fetcher);
  
  if (error) return <div>Failed to load</div>;
  if (!data) return <Loader />;

  const { today, tomorrow } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Surf spots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Surf spots</h1>

        <p className={styles.description}>Hoy</p>
        <div style={{ width: "100%", textAlign: "start" }}>
          {dayHours.map((dayHour) => (
            <>
              <div>
                <div className={styles.dayhour}> {dayHour.label} </div>{" "}
                <BeachItem data={today[dayHour.id]} />
              </div>
              <hr />
            </>
          ))}
        </div>

        <p className={styles.description}>Mañana</p>
        <div style={{ width: "100%", textAlign: "start" }}>
          <hr />
          {dayHours.map((dayHour) => (
            <>
              <div>
                <div className={styles.dayhour}> {dayHour.label} </div>{" "}
                <BeachItem data={tomorrow[dayHour.id]} />
              </div>
              <hr />
            </>
          ))}
      
        </div>

        <h2> Playas</h2>
        {beachs.map((beach, i) => (
          <a key={i} href={beach.url} style={{ width: "100%" }}>
            <h2>{beach.name} &rarr;</h2>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Gonzalo Gras Cantou
        </a>
      </footer>
    </div>
  );
};

export default Home;
